# Generated by Django 2.2.4 on 2019-11-13 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cover_picture', models.ImageField(default='media/drive.png', upload_to='media/<function user_path at 0x7f929e860950>')),
                ('created_at', models.DateTimeField()),
                ('slug', models.SlugField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cover_picture', models.ImageField(default='media/folder-white.png', upload_to='media/<function user_path at 0x7f929e860950>')),
                ('created_at', models.DateTimeField()),
                ('slug', models.SlugField(blank=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Drive')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Folder')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('item', models.FileField(upload_to='media/<function user_path at 0x7f929e860950>')),
                ('cover_picture', models.ImageField(default='media/file.png', upload_to='media/<function user_path at 0x7f929e860950>')),
                ('created_at', models.DateTimeField()),
                ('slug', models.SlugField(blank=True)),
                ('drive', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Drive')),
                ('folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('folder', 'name')},
            },
        ),
    ]
