# Generated by Django 2.2.4 on 2019-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191115_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='cover_picture',
            field=models.ImageField(default='media/drive.png', upload_to='media/<function user_path at 0x7fed8866e950>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='cover_picture',
            field=models.ImageField(default='media/file.png', upload_to='media/<function user_path at 0x7fed8866e950>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(upload_to='media/<function user_path at 0x7fed8866e950>'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='cover_picture',
            field=models.ImageField(default='media/folder-white.png', upload_to='media/<function user_path at 0x7fed8866e950>'),
        ),
    ]
