# Generated by Django 2.2.4 on 2019-11-15 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191115_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drive',
            name='cover_picture',
            field=models.ImageField(default='media/drive.png', upload_to='media/<function user_path at 0x7f096dd6b9d8>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='cover_picture',
            field=models.ImageField(default='media/file.png', upload_to='media/<function user_path at 0x7f096dd6b9d8>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(upload_to='media/<function user_path at 0x7f096dd6b9d8>'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='cover_picture',
            field=models.ImageField(default='media/folder-white.png', upload_to='media/<function user_path at 0x7f096dd6b9d8>'),
        ),
    ]
