# Generated by Django 2.2.4 on 2019-11-15 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191115_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='cover_picture',
            field=models.ImageField(default='media/drive.png', upload_to='media/<function user_path at 0x7f4608d3c9d8>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='cover_picture',
            field=models.ImageField(default='media/file.png', upload_to='media/<function user_path at 0x7f4608d3c9d8>'),
        ),
        migrations.AlterField(
            model_name='file',
            name='item',
            field=models.FileField(upload_to='media/<function user_path at 0x7f4608d3c9d8>'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='cover_picture',
            field=models.ImageField(default='media/folder-white.png', upload_to='media/<function user_path at 0x7f4608d3c9d8>'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Drive'),
        ),
    ]
